const position = { x: 0, y: 0 };

export const initialNodes = [
    {id: '0',type: 'input',data: { label: 'Aerospace Industry' },position},
        {id: '1', data: { label: 'Commercial Aviation' }, position},
            {id: '6', data: { label: 'Airline Operators' }, position},
                {id: '11', data: { label: 'Domestic' }, position},
                {id: '12', data: { label: 'International' }, position},
                            {id: '13', data: { label: 'Passenger Airlines' }, position},
                            {id: '14', data: { label: 'Cargo Airlines' }, position},
                            {id: '21', data: { label: 'Commercial' }, position},
                            {id: '22', data: { label: 'Private' }, position},
            {id: '7', data: { label: 'Aircraft Manufacturers' }, position},
                {id: '15', data: { label: 'Fixed-wing' }, position},
                    {id: '17', data: { label: 'Airplanes' }, position},
                    {id: '18', data: { label: 'Business Jets' }, position},
                {id: '16', data: { label: 'Rotorcraft' }, position},
                    {id: '19', data: { label: 'Helicopters' }, position},
                    {id: '20', data: { label: 'Autogyros' }, position},
            {id: '8', data: { label: 'Airports' }, position},
            {id: '9', data: { label: 'Air Traffic Control' }, position},
                {id: '23', data: { label: 'Radar' }, position},
                    {id: '25', data: { label: 'Primary Surveillance Radar' }, position},
                    {id: '26', data: { label: 'Secondary Surveillance Radar' }, position},
                {id: '24', data: { label: 'Automated' }, position},
                    {id: '27', data: { label: 'Automated Dependent Surveillance-Broadcast' }, position},
                    {id: '28', data: { label: 'Automated Terminal Information Service' }, position},
            {id: '10', data: { label: 'Stocks & Mergers' }, position},
                {id: '29', data: { label: 'Stock Market' }, position},
                    {id: '32', data: { label: 'Stock Exchanges' }, position},
                    {id: '33', data: { label: 'Stock Brokers' }, position},
                {id: '30', data: { label: 'Mergers & Acquisitions' }, position},
                    {id: '34', data: { label: 'Corporate Mergers' }, position},
                    {id: '35', data: { label: 'Corporate Acquisitions' }, position},
                {id: '31', data: { label: 'Corporations' }, position},
                    {id: '36', data: { label: 'Publicly Traded Companies' }, position},
                    {id: '37', data: { label: 'Privately Held Companies' }, position},
        {id: '2', data: { label: 'Military Avaiation' }, position},
        {id: '3', data: { label: 'Space' }, position},
        {id: '4', data: { label: 'Unmanned' }, position},
        {id: '5', data: { label: 'US Government Contracts' }, position},
    ];