const edgeType = 'SmoothStepEdge';

export const initialEdges = [
    { id: 'e01', source: '0', target: '1', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e02', source: '0', target: '2', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e03', source: '0', target: '3', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e04', source: '0', target: '4', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e05', source: '0', target: '5', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e16', source: '1', target: '6', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e17', source: '1', target: '7', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e18', source: '1', target: '8', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e19', source: '1', target: '9', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e110', source: '1', target: '10', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e611', source: '6', target: '11', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e612', source: '6', target: '12', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1113', source: '11', target: '13', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1114', source: '11', target: '14', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1213', source: '12', target: '13', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1214', source: '12', target: '14', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e715', source: '7', target: '15', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e716', source: '7', target: '16', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1517', source: '15', target: '17', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1518', source: '15', target: '18', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1619', source: '16', target: '19', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1620', source: '16', target: '20', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e811', source: '8', target: '11', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e812', source: '8', target: '12', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1121', source: '11', target: '21', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1122', source: '11', target: '22', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1221', source: '12', target: '21', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1222', source: '12', target: '22', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e923', source: '9', target: '23', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e924', source: '9', target: '24', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e2325', source: '23', target: '25', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e2426', source: '23', target: '26', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e2427', source: '24', target: '27', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e2428', source: '24', target: '28', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1029', source: '10', target: '29', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1030', source: '10', target: '30', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e1031', source: '10', target: '31', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e2932', source: '29', target: '32', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e2933', source: '29', target: '33', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e3034', source: '30', target: '34', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e3035', source: '30', target: '35', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e3136', source: '31', target: '36', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }},
    { id: 'e3137', source: '31', target: '37', type: edgeType,animated: true, style: { stroke: '#0ea5e9' }}
    ];
    