const position = { x: 0, y: 0 };

export const initialNodes = [
    {id: '0',type: 'input', data: { label: 'Aerospace Industry' },position},
        {id: '1', type: 'custom', data: { label: 'Commercial Aviation' }, position},
            {id: '6', type: 'custom', data: { label: 'Airline Operators' }, position},
                {id: '11', type: 'custom', data: { label: 'Domestic' }, position},
                {id: '12', type: 'custom', data: { label: 'International' }, position},
                            {id: '13', type: 'custom', data: { label: 'Passenger Airlines' }, position},
                            {id: '14', type: 'custom', data: { label: 'Cargo Airlines' }, position},
                            {id: '21', type: 'custom', data: { label: 'Commercial' }, position},
                            {id: '22', type: 'custom', data: { label: 'Private' }, position},
            {id: '7', type: 'custom', data: { label: 'Aircraft Manufacturers' }, position},
                {id: '15', type: 'custom', data: { label: 'Fixed-wing' }, position},
                    {id: '17', type: 'custom', data: { label: 'Airplanes' }, position},
                    {id: '18', type: 'custom', data: { label: 'Business Jets' }, position},
                {id: '16', type: 'custom', data: { label: 'Rotorcraft' }, position},
                    {id: '19', type: 'custom', data: { label: 'Helicopters' }, position},
                    {id: '20', type: 'custom', data: { label: 'Autogyros' }, position},
            {id: '8', type: 'custom', data: { label: 'Airports' }, position},
            {id: '9', type: 'custom', data: { label: 'Air Traffic Control' }, position},
                {id: '23', type: 'custom', data: { label: 'Radar' }, position},
                    {id: '25', type: 'custom', data: { label: 'Primary Surveillance Radar' }, position},
                    {id: '26', type: 'custom', data: { label: 'Secondary Surveillance Radar' }, position},
                {id: '24', type: 'custom', data: { label: 'Automated' }, position},
                    {id: '27', type: 'custom', data: { label: 'Automated Dependent Surveillance-Broadcast' }, position},
                    {id: '28', type: 'custom', data: { label: 'Automated Terminal Information Service' }, position},
            {id: '10', type: 'custom', data: { label: 'Stocks & Mergers' }, position},
                {id: '29', type: 'custom', data: { label: 'Stock Market' }, position},
                    {id: '32', type: 'custom', data: { label: 'Stock Exchanges' }, position},
                    {id: '33', type: 'custom', data: { label: 'Stock Brokers' }, position},
                {id: '30', type: 'custom', data: { label: 'Mergers & Acquisitions' }, position},
                    {id: '34', type: 'custom', data: { label: 'Corporate Mergers' }, position},
                    {id: '35', type: 'custom', data: { label: 'Corporate Acquisitions' }, position},
                {id: '31', type: 'custom', data: { label: 'Corporations' }, position},
                    {id: '36', type: 'custom', data: { label: 'Publicly Traded Companies' }, position},
                    {id: '37', type: 'custom', data: { label: 'Privately Held Companies' }, position},
        {id: '2', type: 'custom', data: { label: 'Military Avaiation' }, position},
        {id: '3', type: 'custom', data: { label: 'Space' }, position},
        {id: '4', type: 'custom', data: { label: 'Unmanned' }, position},
        {id: '5', type: 'custom', data: { label: 'US Government Contracts' }, position},
    ];